import glob
import json
import os
import pickle
import shutil
from pathlib import Path


def fileToList(f):
    out = open(f, "r").readlines()
    out = [x.strip() for x in out]
    out = [x for x in out if len(x)]
    return out


filter_list = set(fileToList("splits/ignore_list.txt"))
train_list  = set(fileToList("splits/crossmodal_train.txt"))
val_list    = set(fileToList("splits/crossmodal_val.txt"))
test_list   = set(fileToList("splits/crossmodal_test.txt"))


def split_data(dataset_path):
    # train - test split (original solo mode)
    for split_list, split_name in zip([train_list, test_list], ["train", "test"]):
        Path(f"{split_name}/motions").mkdir(parents=True, exist_ok=True)
        Path(f"{split_name}/wavs").mkdir(parents=True, exist_ok=True)
        for sequence in split_list:
            if sequence in filter_list:
                continue
            motion = f"{dataset_path}/motions/{sequence}.pkl"
            wav = f"{dataset_path}/wavs/{sequence}.wav"
            assert os.path.isfile(motion)
            assert os.path.isfile(wav)
            motion_data = pickle.load(open(motion, "rb"))
            trans = motion_data["smpl_trans"]
            pose = motion_data["smpl_poses"]
            scale = motion_data["smpl_scaling"]
            out_data = {"pos": trans, "q": pose, "scale": scale}
            pickle.dump(out_data, open(f"{split_name}/motions/{sequence}.pkl", "wb"))
            shutil.copyfile(wav, f"{split_name}/wavs/{sequence}.wav")


def split_data_duet(dataset_path):
    """Train / test split for the duet task.

    Reads duet_pairs_train.json and duet_pairs_test.json from splits/.
    Each JSON is a list of {"lead": "...", "follower": "..."} objects.
    Both members of every pair are copied to the split folder so the
    dataset loader can find them.  Generated by data/create_duet_pairs.py.
    """
    pairs_train = json.loads(Path("splits/duet_pairs_train.json").read_text())
    pairs_val   = json.loads(Path("splits/duet_pairs_val.json").read_text())
    pairs_test  = json.loads(Path("splits/duet_pairs_test.json").read_text())

    for pairs, split_name in [(pairs_train, "train"), (pairs_val, "val"), (pairs_test, "test")]:
        Path(f"{split_name}/motions").mkdir(parents=True, exist_ok=True)
        Path(f"{split_name}/wavs").mkdir(parents=True, exist_ok=True)
        copied = 0
        seen   = set()  # skip sequences that appear in multiple pairs
        for pair in pairs:
            for sequence in (pair["lead"], pair["follower"]):
                if sequence in seen or sequence in filter_list:
                    continue
                seen.add(sequence)
                motion = f"{dataset_path}/motions/{sequence}.pkl"
                wav    = f"{dataset_path}/wavs/{sequence}.wav"
                if not os.path.isfile(motion) or not os.path.isfile(wav):
                    print(f"  [SKIP] missing: {sequence}")
                    continue
                motion_data = pickle.load(open(motion, "rb"))
                out_data = {
                    "pos":   motion_data["smpl_trans"],
                    "q":     motion_data["smpl_poses"],
                    "scale": motion_data["smpl_scaling"],
                }
                pickle.dump(out_data, open(f"{split_name}/motions/{sequence}.pkl", "wb"))
                shutil.copyfile(wav, f"{split_name}/wavs/{sequence}.wav")
                copied += 1
        print(f"  {split_name}: {copied} sequences copied")
